### PR TITLE
v0.5.13

### PR DESCRIPTION
**Pull request by ozak**

### CODE REVIEW

**Comment by ozak** [comment]
@CJ-Wright @jjhelmus do you know how one can force the build and tests to use ``conda-forge`` as the channel? The CI build & test seem to be failing because it is installing ``libgdal`` from ``default`` instead of using the ``conda-forge`` version [(see here)](https://github.com/conda-forge/gdal-feedstock/issues/201). Should I add something in the recipe? Or do I need to add a ``.condarc`` file to the recipe? Where?

Also the ``linter`` is complaining although I have not changed anything in the file (besides the version number, link and sha256. Was there a change that is not reflected in the current online examples?

Any help is appreciated. Thanks!

**Comment by djsutherland** [comment]
@ozak The linter problem was a temporary bug in the linter, which has been fixed; sorry about that.

`libgdal` coming from `defaults` is an overall problem right now. @ocefpaf, do you know if there's a general workaround to use?

**Comment by ocefpaf** [comment]
> @ocefpaf, do you know if there's a general workaround to use?

Just a hack-y workaround of removing `defaults` from our builds:

https://github.com/conda-forge/geopandas-feedstock/pull/43/commits/b6646d68456166ef94b12beca6d4c860aec18dbd#diff-a90a4657917102fb3eb936be494d9da3L15

Terrible solution but it works.

**Comment by ozak** [comment]
Thanks for getting back to me. 

@ocefpaf from what I see in the CI output ``conda-forge`` comes the channel before ``default``. Does setting it up in ``.circleci/build_steps.sh`` make a difference? Or am I misreading the output?

**Comment by ocefpaf** [comment]
> Does setting it up in .circleci/build_steps.sh make a difference? 

It does. If you remove `defaults` from that file you should get all packages from `conda-forge` in that build.

**Comment by ocefpaf** [comment]
@ozak let's re-render first just to get this up-to-date and then we can make that modification, hold on...

@conda-forge-admin, please rerender

**Comment by ozak** [comment]
@ocefpaf just to make sure I understand the process...did you create the ``build_steps.sh`` file? Is this file recreated every time by the system or does it keep the one I create?

**Comment by ocefpaf** [comment]
> @ocefpaf just to make sure I understand the process...did you create the build_steps.sh file? 

Nope. That comes from the re-rendering. We should always re-render first to get the latest config from conda-forge.

> Is this file recreated every time by the system or does it keep the one I create?

It will be re-created every time we re-render and the hack edit I made in the last commit will be lost! That is why we need a long term solution for that.

(We, conda-forge core members, are discussing that right now.)

**Comment by ozak** [comment]
So basically I cannot do anything on my end and any update will require me to ping you guys until we have a solution?

**Comment by ocefpaf** [comment]
> So basically I cannot do anything on my end and any update will require me to ping you guys until we have a solution?

Not really. You just reverted the solution we have at the moment :-(

**Comment by ozak** [comment]
Sorry...I had created the file on my side by the time you wrote...now I deleted the commit...still learning.

**Comment by ocefpaf** [comment]
@ozak I'm re-rendering it again. Please do not revert any commits or the changes won't make any effect.

@conda-forge-admin, please rerender

**Comment by ocefpaf** [comment]
> Sorry...I had created the file on my side by the time you wrote...now I deleted the commit...still learning.

No problem. Let the re-rendering on `conda-smithy` do that for you.

**Comment by ocefpaf** [comment]
:tada: passing!

Note that to install it you will also need to restrict your channel to conda-forge `only` with something like:

```
conda create --name TEST --override-channels --channel conda-forge georasters
```

**Comment by ozak** [comment]
Great! Thanks for the help!

**Pull request merged**
